### ISSUE TITLE
Disease_ With_ Relationship_ To_ genes.pickle file

### ISSUE THREAD

**Issue by xuzhaoyang-svg** [BaranziniLab/KG_RAG#15]
Thanks for your work. What data does the Disease_ With_ Relationship_ To_ genes.pickle file contain? And how to create this file?

**Comment by karthiksoman** [comment]
Hi @xuzhaoyang-svg 
**disease_with_relation_to_genes.pickle** holds the names of diseases whose vectors are computed and stored in vectorDB. Here, we only chose those disease names that have a relationship with _Genes_ in the biomedical knowledge graph called [SPOKE](https://spoke.rbvi.ucsf.edu/). Hence the name **disease_with_relation_to_genes**.
This file was created by running a CYPHER query against the SPOKE graph (in neo4j):
```
MATCH(d:Disease)-[r:ASSOCIATES_DaG]->(g:Gene)
RETURN d.name AS d_name
```
Let me know if this answers your question.

**Comment by xuzhaoyang-svg** [comment]
Store the query results obtained from the CYPHER query in . pickle file format by calculating vectors.

**Comment by karthiksoman** [comment]
It is stored in pickle file format 'for computing vectors' NOT 'by calculating vectors'. Let me know if that clarifies your question.

**Comment by xuzhaoyang-svg** [comment]
Thank you, I understand now.

**Comment by karthiksoman** [comment]
Awesome! I am closing this issue then.
