### ISSUE TITLE
No response from SPOKE api

### ISSUE THREAD

**Issue by janjoy** [BaranziniLab/KG_RAG#30]
Hello!
I have been trying to get some response from SPOKE server and getting Error 500. It's been happening on and off. The server seems down. Any idea when it will be resolved?
Best,
Janet

![Spoke_server_down](https://github.com/BaranziniLab/KG_RAG/assets/65145105/6f3a8ff4-de6f-4551-be8a-70d2410e50bc)

**Comment by karthiksoman** [comment]
That was because of a server side issue. That is been corrected now. SPOKE is now up and running.

**Comment by weiyifan1023** [comment]
Recently, I also encountered this problem, which has been going on for a week, is the SPOKE server often inaccessible, and how can I solve it?
