### ISSUE TITLE
disease_nodes_db

### ISSUE THREAD

**Issue by yiyangfelix** [BaranziniLab/KG_RAG#33]
Hi, 

I have a question about the vector_db_path in the config.yaml. What is the diseases_nodes_db here? Thank you

**Comment by fjfd** [comment]
it appears to be entity node data in knowledge graph!

**Comment by karthiksoman** [comment]
@yiyangfelix apologies for the late response! VECTOR_DB_PATH in the cofig.yaml file is the name of the chroma vector db that will be created when running 
```
python -m kg_rag.run_setup
```
In the backend, it runs the script
```
create_vectordb.py
```
You can find that script [here](https://github.com/BaranziniLab/KG_RAG/blob/main/kg_rag/vectorDB/create_vectordb.py) and note Line no. 6 there, where it uses the VECTOR_DB_PATH as the name to create the database.
