### ISSUE TITLE
In disease_entity_extractor_v2 the system prompt gets repeated twice

### ISSUE THREAD

**Issue by hyunwhanjoe** [BaranziniLab/KG_RAG#40]
Hi, I was just wondering in utility.py line 243 for the definition of disease_entity_extractor_v2, why the system prompt is included in prompt_updated because by including it, the system prompt gets repeated twice when calling OpenAI.

**Comment by karthiksoman** [comment]
Yes, this was done intentionally. Initially, we provided the system prompt only once, as the system prompt itself. However, we noticed that this method occasionally missed detecting certain disease entities in user queries. We then tried incorporating the system prompt as an additional instruction within the user prompt, which successfully handled these edge cases and improved the detection of disease entities.
